### 
POST http://localhost:3000/styles/07247cc8-a476-47e3-987b-c8dcd9e129be/curations
Content-Type: application/json

{
	"nickname": "손훈석",
	"content": "좀 치는데요?",
	"password": "a123456789",
	"trendy": 4,
	"personality": 6,
	"practicality": 8,
	"costEffectiveness": 10
}

### 
GET http://localhost:3000/styles/07247cc8-a476-47e3-987b-c8dcd9e129be/curations

### 
PUT http://localhost:3000/curations/21fbf7a1-cc0b-46a8-a06b-bf7f3eb4333e
Content-Type: application/json

{
	"nickname": "손석훈",
	"content": "사실 별로임",
	"password": "a123456789",
	"trendy": 2,
	"personality": 4,
	"practicality": 6,
	"costEffectiveness": 8
}


###
DELETE http://localhost:3000/curations/21fbf7a1-cc0b-46a8-a06b-bf7f3eb4333e
Content-Type: application/json

{
	"password": "a123456789"
}

