### 
POST http://localhost:4000/styles/a4cdb85c-05f5-4175-b194-940d5b115547/curations
Content-Type: application/json

{
	"nickname": "손훈석",
	"content": "좀 치는데요?",
	"password": "a123456789",
	"trendy": 4,
	"personality": 6,
	"practicality": 8,
	"costEffectiveness": 10
}

### 
GET http://localhost:4000/styles/a4cdb85c-05f5-4175-b194-940d5b115547/curations

### 
PUT http://localhost:4000/curations/abdfb728-d381-4e4f-a023-3fc46ac3e872
Content-Type: application/json

{
	"nickname": "손석훈",
	"content": "사실 별로임",
	"password": "a123456789",
	"trendy": 2,
	"personality": 4,
	"practicality": 6,
	"costEffectiveness": 8
}


###
DELETE http://localhost:4000/curations/abdfb728-d381-4e4f-a023-3fc46ac3e872
Content-Type: application/json

{
	"password": "a123456789"
}

