GET http://localhost:3000/howdoilook/comments

###

POST http://localhost:3000/howdoilook/comments
Content-Type: application/json

{
  "nickname": "string",
	"content": "string",
	"password": "string"
}

###

PATCH http://localhost:3000/howdoilook/comments/bd28da67-84b6-4926-8457-f5a208df5bb1
Content-Type: application/json

{
  "content": "사실 이건 node가 아니야 !"
}

###

DELETE http://localhost:3000/products/62bf47c6-c41c-4b0e-b232-86c37a220ff5